import Head from 'next/head'
import '../styles/globals.css' // Assuming your global styles are in 'styles/globals.css'

export const metadata = {
	title: 'Expenses tracker',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<Head>
				<link
					rel='stylesheet'
					href={`https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap`}
				/>
			</Head>
			<body>{children}</body>
		</html>
	)
}
